
name: 'terraform_plan'

on:
  push:
    branches:
    - main
jobs:
  terraform:
    name: "Terraform plan"
    runs_on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ID }}
      AWS_REGION: "us-east-1"
      steps:
        - name: Checkout
          uses: actions/checkout@v2 
        - name : Setup Terraform
          uses: hashicorp/setup-terraform@v1

