
name: 'terraform_plan'
on:
  push:
    branches:
    - main
jobs:
  env: 
    AWS_ACCESS_KEY_ID: ${{secrets.AWS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_ID}}
    AWS_REGION: 'us-east-1'


  basic-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        id : init 
        run: terraform init

      - name: Terraform plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color



