
name: 'terraform_plan'
on:
  push:
    branches:
    - main
jobs:

  basic-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        uses: terraform init

      - name: Terraform plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color



