name: 'terraform_plan'
on:
  push:
    branches:
    - main

jobs:
    terraform_apply:
        runs-on: ubuntu-latest
        env: 
            AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            AWS_REGION: 'us-east-1'

        steps:
            - name: Checkout
              uses: actions/checkout@v4
      
            - name: Setup terraform
              uses: hashicorp/setup-terraform@v3
      
            - name: Terraform init
              id : init 
              run: terraform init

                    
            - name: Terraform plan
              id : plan 
              run: terraform plan -no-color

            - name: Terraform apply
              id: apply
              if: github.event_name == 'push'
              run: terraform destroy -auto-approve